sudo: required

language: java

jdk:
  - openjdk8

branches:
  only:
    - master
    - stable

install: true

script:
  - ./gradlew clean build --no-daemon

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew bintrayUpload
    on:
      branch: master
